### ISSUE TITLE
Library not usable

### ISSUE THREAD

**Issue by majuss** [adafruit/Adafruit_CircuitPython_SSD1322#21]
I have a single line:
```import adafruit_ssd1322```

On a Raspberry Pi 4 3.11.2
This already fails with:
```
Traceback (most recent call last):
  File "/home/pi/displaytestvenv/test.py", line 2, in <module>
    import adafruit_ssd1322
  File "/home/pi/displaytestvenv/lib/python3.11/site-packages/adafruit_ssd1322.py", line 67, in <module>
    class SSD1322(displayio.Display):
                  ^^^^^^^^^^^^^^^^^
AttributeError: module 'displayio' has no attribute 'Display'. Did you mean: 'displays'?
```

**Comment by dastels** [comment]
Are all the modules/libraries up to date?

**Comment by majuss** [comment]
yes fresh venv.

**Comment by FoamyGuy** [comment]
I think the class that the the driver extends at the class definition here: https://github.com/adafruit/Adafruit_CircuitPython_SSD1322/blob/986794594b53956068a26a49d4ad66c3f4cdfbc4/adafruit_ssd1322.py#L67 needs to change to [busdisplay.BusDisplay](https://docs.circuitpython.org/en/latest/shared-bindings/busdisplay/index.html#busdisplay.BusDisplay) in order to be used on the latest versions of circuitpython core.

**Comment by FoamyGuy** [comment]
This should be resolved by https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/136 I don't have this exact display to test but tried to get as close as possible with a different display driver modified to make it like this one. 

Please update to the latest Blinka_DisplayIO version and try again. If you still have any issues feel free to re-open this or create a new one if appropriate.
